"""Initial migration for PostgreSQL

Revision ID: 502403ac628d
Revises: 
Create Date: 2024-12-11 21:45:15.257239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '502403ac628d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tennis_club',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('subdomain', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tennis_club', schema=None) as batch_op:
        batch_op.create_index('idx_tennis_club_subdomain', ['subdomain'], unique=True)

    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('contact_email', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('tennis_club_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tennis_club_id'], ['tennis_club.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teaching_period',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('tennis_club_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tennis_club_id'], ['tennis_club.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tennis_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('tennis_club_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tennis_club_id'], ['tennis_club.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.Enum('COACH', 'ADMIN', 'SUPER_ADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('auth_provider', sa.String(length=20), nullable=True),
    sa.Column('auth_provider_id', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('tennis_club_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tennis_club_id'], ['tennis_club.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('idx_user_email_lower', [sa.text('lower(email)')], unique=True)

    op.create_table('coach_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tennis_club_id', sa.Integer(), nullable=False),
    sa.Column('coach_number', sa.String(length=50), nullable=True),
    sa.Column('qualification', sa.Enum('LEVEL_1', 'LEVEL_2', 'LEVEL_3', 'LEVEL_4', 'LEVEL_5', 'NONE', name='coachqualification'), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('contact_number', sa.String(length=20), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=100), nullable=True),
    sa.Column('emergency_contact_number', sa.String(length=20), nullable=True),
    sa.Column('address_line1', sa.String(length=100), nullable=True),
    sa.Column('address_line2', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('postcode', sa.String(length=10), nullable=True),
    sa.Column('coach_role', sa.Enum('HEAD_COACH', 'SENIOR_COACH', 'LEAD_COACH', 'ASSISTANT_COACH', 'JUNIOR_COACH', name='coachrole'), nullable=True),
    sa.Column('utr_number', sa.String(length=20), nullable=True),
    sa.Column('accreditation_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bcta_accreditation', sa.String(length=10), nullable=True),
    sa.Column('dbs_number', sa.String(length=50), nullable=True),
    sa.Column('dbs_issue_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dbs_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dbs_update_service_id', sa.String(length=50), nullable=True),
    sa.Column('pediatric_first_aid', sa.Boolean(), nullable=True),
    sa.Column('pediatric_first_aid_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_aid_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('safeguarding_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tennis_club_id'], ['tennis_club.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coach_number'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('programme_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('teaching_period_id', sa.Integer(), nullable=False),
    sa.Column('tennis_club_id', sa.Integer(), nullable=False),
    sa.Column('report_submitted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['coach_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['tennis_group.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.ForeignKeyConstraint(['teaching_period_id'], ['teaching_period.id'], ),
    sa.ForeignKeyConstraint(['tennis_club_id'], ['tennis_club.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('teaching_period_id', sa.Integer(), nullable=False),
    sa.Column('programme_player_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('forehand', sa.String(length=20), nullable=True),
    sa.Column('backhand', sa.String(length=20), nullable=True),
    sa.Column('movement', sa.String(length=20), nullable=True),
    sa.Column('overall_rating', sa.Integer(), nullable=True),
    sa.Column('next_group_recommendation', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['coach_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['tennis_group.id'], ),
    sa.ForeignKeyConstraint(['programme_player_id'], ['programme_players.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.ForeignKeyConstraint(['teaching_period_id'], ['teaching_period.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report')
    op.drop_table('programme_players')
    op.drop_table('coach_details')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('idx_user_email_lower')

    op.drop_table('user')
    op.drop_table('tennis_group')
    op.drop_table('teaching_period')
    op.drop_table('student')
    with op.batch_alter_table('tennis_club', schema=None) as batch_op:
        batch_op.drop_index('idx_tennis_club_subdomain')

    op.drop_table('tennis_club')
    # ### end Alembic commands ###
